PATH_TO_ATTACHED_FILE = "~/Documents/example.txt"
LOGIN_ADDRESS = "https://account.proton.me/mail"
INBOX_ADDRESS = "https://mail.proton.me/u/0/inbox"
PASSWORD = "2Rqp&:4W*%HX]8y"
EMAIL = "test46546@protonmail.com"
